apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBaseline
metadata:
  name: baseline-workloads
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
      - apiGroups: ["argoproj.io"]
        kinds: ["Rollout"]
  parameters:
    requiredLabels:
      - Environment
      - Project
      - ManagedBy
