apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:operator, applications, get, */*, allow
    p, role:operator, applications, sync, workloads/*, allow
    p, role:operator, applications, sync, platform-addons/*, allow
    p, role:operator, logs, get, */*, allow
    p, role:operator, exec, create, workloads/*, deny
    g, platform-operators, role:operator
