apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  description: Metrics, logs, traces, dashboards, and SLO rules.
  sourceRepos:
    - https://github.com/adityanep1/DriftGuard.git
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: monitoring
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: monitoring.coreos.com
      kind: PrometheusRule
    - group: monitoring.coreos.com
      kind: ServiceMonitor
