apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-addons
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  description: Platform controllers delivered by ArgoCD.
  sourceRepos:
    - https://github.com/your-org/driftguard-gitops.git
    - https://argoproj.github.io/argo-helm
    - https://aws.github.io/eks-charts
    - https://charts.external-secrets.io
    - https://open-policy-agent.github.io/gatekeeper/charts
    - https://falcosecurity.github.io/charts
    - oci://public.ecr.aws/karpenter
    - https://charts.crossplane.io/stable
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: karpenter
    - server: https://kubernetes.default.svc
      namespace: aws-load-balancer-controller
    - server: https://kubernetes.default.svc
      namespace: external-secrets
    - server: https://kubernetes.default.svc
      namespace: gatekeeper-system
    - server: https://kubernetes.default.svc
      namespace: argo-rollouts
    - server: https://kubernetes.default.svc
      namespace: falco
    - server: https://kubernetes.default.svc
      namespace: crossplane-system
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: pkg.crossplane.io
      kind: Provider
    - group: pkg.crossplane.io
      kind: ProviderRevision
    - group: apiextensions.crossplane.io
      kind: CompositeResourceDefinition
    - group: apiextensions.crossplane.io
      kind: Composition
    - group: aws.upbound.io
      kind: ProviderConfig
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: apps
      kind: DaemonSet
    - group: apps
      kind: StatefulSet
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: karpenter.sh
      kind: NodePool
    - group: karpenter.k8s.aws
      kind: EC2NodeClass
    - group: storage.driftguard.io
      kind: Bucket
