apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-prod
resources:
  - ../../base
commonLabels:
  Environment: prod
images:
  - name: ghcr.io/your-org/demo-service
    newName: 123456789012.dkr.ecr.us-east-1.amazonaws.com/driftguard-prod/demo-service
    newTag: REPLACE_WITH_COMMIT_SHA
