apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-service-config
  namespace: demo-dev
  labels:
    app.kubernetes.io/name: demo-service-config
    app.kubernetes.io/part-of: driftguard
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: demo-service-config
    creationPolicy: Owner
  data:
    - secretKey: upstream-token
      remoteRef:
        key: driftguard/demo-service
        property: upstream-token
