apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: demo-dev
  labels:
    app.kubernetes.io/name: aws-secrets-manager
    app.kubernetes.io/part-of: driftguard
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: demo-service
