apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - service.yaml
  - service-canary.yaml
  - ingress.yaml
  - rollout.yaml
  - analysis-templates.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: driftguard
      Project: DriftGuard
      ManagedBy: ArgoCD
    includeSelectors: false
